branches:
- coreweave
preset: "angular"
tagFormat: "v${version}-cw"
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/exec"
repositoryUrl: "git@github.com:coreweave/sriov-network-device-plugin.git"
analyzeCommits:
- path: "@semantic-release/commit-analyzer"
  releaseRules:
  - type: "feature"
    release: "minor"
  - type: "update"
    release: "minor"
  - type: "refactor"
    release: "patch"
  - type: "fix"
    release: "patch"
  - type: "docs"
    release: "patch"
  parserOpts:
    noteKeywords:
    - "BREAKING CHANGE"
    - "BREAKING CHANGES"
publish:
- path: "@semantic-release/exec"
  publishCmd: |-
    export RELEASE_IMAGE=$IMAGE_NAME:v${nextRelease.version}-cw &&
    crane push $CI_PROJECT_DIR/image.tar $RELEASE_IMAGE
    